data_path: ./data/Chicago_Sketch/ #./data/Sioux_Falls/ #
demand_randomness: False #False
avail_initial_path_flow: False #True

optimization_setting:
  training_steps: 1000
  learning_rates: 0.01

data_imputation:
  car_prop: 0.9
  truck_prop: 0.1